### ISSUE TITLE
Help Wanted – Troubleshooting, Tips, and Tricks

### ISSUE THREAD

**Issue by kristywa** [awsdocs/aws-elemental-mediastore-user-guide#1]
Please share your experience! If you hit a problem and solved it, I’d love to hear from you. I am also interested in any tips or tricks you’ve learned along the way.

Submit a pull request (directions [here](https://github.com/awsdocs/aws-elemental-mediastore-user-guide/blob/master/CONTRIBUTING.md)) or send me a note via the Comments below. If your suggestion is likely to help others, I'll add it to the [AWS Elemental MediaStore User Guide](https://docs.aws.amazon.com/mediastore/latest/ug/what-is.html). 

Thank you for your time. I look forward to hearing from you!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
